import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Stickybottom from "@/components/Stickybottom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { icons } from "lucide-react";
import Whatsapp from "@/components/Whatsapp";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App ",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.webp'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Whatsapp></Whatsapp>
        <Navbar/>
        {children}
          <Stickybottom />
         <Footer/>
      </body>
    </html>
  );
}
